module.exports = {
    SAVE_CONTACT: 'SAVE_CONTACT',
    RECIEVE_CONTACTS: 'RECIEVE_CONTACTS',
    REMOVE_CONTACT: 'REMOVE_CONTACT',
    EDIT_CONTACT: 'EDIT_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT'

}